CREATE TABLE IF NOT EXISTS tasks (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    done BOOLEAN NOT NULL DEFAULT FALSE
);

INSERT INTO tasks (name, done)
VALUES
('Check in for work', true),
('Attend morning stand-up meeting', true),
('Reply to emails', false),
('Complete assigned tasks', false),
('Review pull requests', true),
('Join client meeting', false),
('Submit daily report', false),
('Check out at end of day', false);